name: Frontix CI/CD

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*" # when you push a tag like v1.0.0
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run type checking
      - name: Run TypeScript type check
        run: npm run type-check

      # Run tests
      - name: Run tests
        run: npm test

      # Run test coverage
      - name: Run test coverage
        run: npm run test:coverage

      # Build package
      - name: Build package
        run: npm run build

      # Upload coverage reports
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') # only on version tags

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js for npm publish
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build package before publishing
      - name: Build package
        run: npm run build

      # Publish to npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
